### ISSUE TITLE
feat: `EnableBlame`, `DisableBlame` 

### ISSUE THREAD

**Issue by IndianBoy42** [FabijanZulj/blame.nvim#1]
It would be nice if there was direct enable and disable commands/functions.

For me I bind a bunch of clearing visual  commands to <esc> like `nohlsearch` so DisableBlame would go there.

**Comment by FabijanZulj** [comment]
I see. Seems that it would be valuable Ill add it

Thanks :)

**Comment by FabijanZulj** [comment]
Added the Enable and Disable with #8
