### ISSUE TITLE
Missing commit message

### ISSUE THREAD

**Issue by gukz** [FabijanZulj/blame.nvim#13]

**Comment by TamasBarta** [comment]
I agree this should be added. The execution of the plugin is flawless, I'm certainly impressed, but without seeing the commit message in some way, this seems to have very limited uses. The author may be important too for most, but usually I use blame to see the reason for a specific change, that I could find out from the commit message.

You could consider providing a string format option that can use the commit message trimmed to arbitrary lengths, similarly to how we can format the date. What do you think?

**Comment by brownLlama** [comment]
highly waiting for this.

**Comment by gukz** [comment]
> You could consider providing a string format option that can use the commit message trimmed to arbitrary lengths, similarly to how we can format the date. What do you think?

Good for me
