### ISSUE TITLE
Command name: Should it be "BlameEnable"?

### ISSUE THREAD

**Issue by okuramasafumi** [FabijanZulj/blame.nvim#18]
I noticed that the patterns of command name is different from other plugins.
Specifically, "FooToggle" is more common than "ToggleFoo". This seems a typical convention.

Example:
https://github.com/folke/trouble.nvim?tab=readme-ov-file#commands

So my proposal is to rename "Enable" to "BlameEnable". What do you think?

**Comment by FabijanZulj** [comment]
Oh I see.
I agree that this should have been the other way,
but I don't think its such a big deal to warrant breaking peoples configs.

Ill leave it open as its a valid observation and should be visible somewhere

**Comment by okuramasafumi** [comment]
I'd like to suggest creating aliases for `EnableBlame`, and then deprecating `EnableBlame`, and finally removing it.

**Comment by FabijanZulj** [comment]
There is only BlameToggle command now in the latest version
