### ISSUE TITLE
Alignment in virtual mode

### ISSUE THREAD

**Issue by syyyr** [FabijanZulj/blame.nvim#3]
Hi, I really like the plugin's virtual mode, but I have a very wide monitor and so the "blames" are very far from the code. I have a few ideas:
- Add a feature to set a padding from the right.
- Put the blames directly after every line. They wouldn't be aligned, but that's fine by me.
- Align the blames by the longest line in the file (possibly with some padding, as in the window mode).

![image](https://github.com/FabijanZulj/blame.nvim/assets/17759291/0f57d7f7-d83a-47e3-a2b2-8a8088785929)

What do you think?

**Comment by FabijanZulj** [comment]
Yes sounds like a problem :)
Best solution would be to align them by the longest line with some padding I guess.
Ill try adding that
