### ISSUE TITLE
Support file renaming in older commits

### ISSUE THREAD

**Issue by ouuan** [FabijanZulj/blame.nvim#31]
The "blame stack" feature should use the `commit.filename` instead of the initial filename on pushing, in case that the file was renamed in older commits.

Basically, we need this change:

```diff
@@ -216,6 +216,8 @@ function BlameStack:push(commit)
         })
     end
 
+    self.file_path = commit.filename
+
     vim.api.nvim_set_current_win(self.original_window)
     vim.api.nvim_set_current_buf(self.stack_buffer
```

However, I'm messed up with cwd and other commands and haven't figured out how to properly handle them.

**Comment by FabijanZulj** [comment]
Hmm, Is this a reliable way to follow renames? 
If it is, awesome! Ill figure out cwd with git root and relative/absolute paths.

Appreciate the input :)

**Comment by ouuan** [comment]
> Hmm, Is this a reliable way to follow renames?

It seems so. I'm not sure if it's reliable, but it works in my test.
