### ISSUE TITLE
The option -w for git blame

### ISSUE THREAD

**Issue by JanosSarkoezi** [FabijanZulj/blame.nvim#44]
Please add the -w option to git blame.

Update: please take a look at https://github.com/JanosSarkoezi/blame.nvim/commit/7081043012838ea1d875581e682bdb0bf1e857bc
This is my solution to my ticket and possibly other tickets too. If you like this, do the customization or merge.

**Comment by FabijanZulj** [comment]
Thanks, it looks great. It resolves #44 too! We should merge it
